### ISSUE TITLE
这个要是通过DeepL翻译成中文，是不是更好？

### ISSUE THREAD

**Issue by fenggit** [evmn/Paul-Graham#1]
这个要是通过DeepL翻译成中文，是不是更好？

**Comment by evmn** [comment]
如果你有兴趣，并且愿意付出很多时间和精力，可以新建一个项目，使用工具翻译、人工校正。如果质量不错，我会添加你的项目链接。

我认为再智能的机器，也难以像人类一样比较准确的理解作者的思想。

我今天看了作者的一篇文章**Relentlessly Resourceful**，文中提到一个词语hapless，作者认为词典上的解释不够好。如果我们让机器去处理这篇文章，我们虽然看的更快，但肯定有很多地方看的一头雾水，不知所云，不得不回去看原文。

下面是谷歌翻译的效果：

>几天前，我终于成为一名优秀的创业公司创始人，归结为两个词：无情的足智多谋。

>在那之前，我所做的最好的事情就是将相反的质量归结为一个：倒霉。 大多数词典都说倒霉就是倒霉。 但是字典做的不是很好。 一支击败对手但因裁判失误而输球的球队可以被称为不幸，但并非不幸。 不幸意味着被动。 倒霉就是被环境所打击——让世界随你而行，而不是随你随世。 


我认为即使花更多时间反复阅读一篇文章，也比快速看完所有文章的劣质译文要好的多。如果我们花几个月甚至一两年把作者几十年的经验学到脑子里，也比快速看很多书却没有深刻理解，最后到处踩坑积累经验要好的多。

**Comment by fenggit** [comment]
> 如果你有兴趣，并且愿意付出很多时间和精力，可以新建一个项目，使用工具翻译、人工校正。如果质量不错，我会添加你的项目链接。
> 
> 我认为再智能的机器，也难以像人类一样比较准确的理解作者的思想。
> 
> 我今天看了作者的一篇文章**Relentlessly Resourceful**，文中提到一个词语hapless，作者认为词典上的解释不够好。如果我们让机器去处理这篇文章，我们虽然看的更快，但肯定有很多地方看的一头雾水，不知所云，不得不回去看原文。
> 
> 下面是谷歌翻译的效果：
> 
> > 几天前，我终于成为一名优秀的创业公司创始人，归结为两个词：无情的足智多谋。
> 
> > 在那之前，我所做的最好的事情就是将相反的质量归结为一个：倒霉。 大多数词典都说倒霉就是倒霉。 但是字典做的不是很好。 一支击败对手但因裁判失误而输球的球队可以被称为不幸，但并非不幸。 不幸意味着被动。 倒霉就是被环境所打击——让世界随你而行，而不是随你随世。
> 
> 我认为即使花更多时间反复阅读一篇文章，也比快速看完所有文章的劣质译文要好的多。如果我们花几个月甚至一两年把作者几十年的经验学到脑子里，也比快速看很多书却没有深刻理解，最后到处踩坑积累经验要好的多。

是的，应该是我没表达清楚，用DeepL翻译后，要人为校验的；“我认为再智能的机器，也难以像人类一样比较准确的理解作者的思想。” 这点我是很赞同的

**Comment by evmn** [comment]
阮一峰老师翻译的《黑客与画家》已经包含了作者网站上的十多篇优质文章。

你可以考虑只翻译自己喜欢的文章，或者[作者最喜欢的文章](https://twitter.com/paulg/status/1207995301535080449)，即使少数几篇翻译排版比较好的文章，也可能会吸引大量网友。

如果有时间，我可能也会参与进去。

**Comment by qianguyihao** [comment]
厉害了

**Comment by qianguyihao** [comment]
整理得很棒，可以认识一下你么？ @evmn

**Comment by evmn** [comment]
可以啊
